LICENSE.md
build.py
clang_3.8/.dockerignore
clang_3.8/Dockerfile
clang_3.9/.dockerignore
clang_3.9/Dockerfile
clang_4.0/.dockerignore
clang_4.0/Dockerfile
gcc_4.6/.dockerignore
gcc_4.6/Dockerfile
gcc_4.8/.dockerignore
gcc_4.8/Dockerfile
gcc_4.9/.dockerignore
gcc_4.9/Dockerfile
gcc_5.2/.dockerignore
gcc_5.2/Dockerfile
gcc_5.3/.dockerignore
gcc_5.3/Dockerfile
gcc_5.4/.dockerignore
gcc_5.4/Dockerfile
gcc_6.2/.dockerignore
gcc_6.2/Dockerfile
gcc_6.3/.dockerignore
gcc_6.3/Dockerfile
gcc_7.2/.dockerignore
gcc_7.2/Dockerfile

Hi!
I just started to refactoring the images, but I'll keep this PR as [work-in-progress] in order to receive  comments during this task. As we have many images, the final state before to merge can be huge and tedious to review.
For now, I reduced about 100MB from conangcc63
Regards.

Refactoring Docker images

---

.travis.yml
README.md
clang_5.0/.dockerignore
clang_5.0/Dockerfile
clang_5.0/build.sh
clang_5.0/run.sh
clang_5.0/test.sh

Hi!
This PR brings the support to build any project using Conan + Clang 5.0
Closes #13 
Regards!

Add support to CLang 5.0

---

.travis.yml
README.md
build.py
docker-compose.yml

Hi!
This PR brings the support to use Docker compose!
Also, It's possible to configure the tag name by `DOCKER_BUILD_TAG`  
By default, the tag **latest** will be used, but you can configure as env var, e.g. 0.28.1  
There is no way to apply multiple tags using docker-compose for now.
So, anyone will be able to build any image by builld.py or directly invoking docker-compose.
Regards!

Build and Test using Docker Compose

---

clang_3.9-i386/Dockerfile
clang_4.0-i386/Dockerfile
clang_5.0-i386/Dockerfile
gcc_4.9-i386/Dockerfile
gcc_4.9/Dockerfile
gcc_5-i386/Dockerfile
gcc_6-i386/Dockerfile
gcc_7-i386/Dockerfile

Fixing 4.9 based on trusty and entrypoint for i686 in 32 bit images

---

clang_3.8/Dockerfile
clang_3.9-i386/Dockerfile
clang_3.9/Dockerfile
clang_4.0-i386/Dockerfile
clang_4.0/Dockerfile
clang_5.0-i386/Dockerfile
clang_5.0/Dockerfile
conan_server/Dockerfile
gcc_4.6/Dockerfile
gcc_4.8/Dockerfile
gcc_4.9-i386/Dockerfile
gcc_4.9/Dockerfile
gcc_5-i386/Dockerfile
gcc_5.2/Dockerfile
gcc_5.3/Dockerfile
gcc_5.4/Dockerfile
gcc_5/Dockerfile
gcc_6-i386/Dockerfile
gcc_6.2/Dockerfile
gcc_6.3/Dockerfile
gcc_6.4/Dockerfile
gcc_6/Dockerfile
gcc_7-i386/Dockerfile
gcc_7.2/Dockerfile
gcc_7/Dockerfile
update_cmake.py

Related issue: https://github.com/conan-io/conan-docker-tools/issues/40
Hi!
This PR brings 3 changes:
- CMake version update 3.10.1 to 3.10.3
- Conan server update 1.0.3 to 1.1.1
- Install pkg-config in ALL images
/cc @pvicente 
Regards.

Install pkgconfig

---

clang_3.8/Dockerfile
clang_3.9-x86/Dockerfile
clang_3.9/Dockerfile
clang_4.0-x86/Dockerfile
clang_4.0/Dockerfile
clang_5.0-x86/Dockerfile
clang_5.0/Dockerfile
clang_6.0-x86/Dockerfile
clang_6.0/Dockerfile
gcc_4.6/Dockerfile
gcc_4.8/Dockerfile
gcc_4.9-x86/Dockerfile
gcc_4.9/Dockerfile
gcc_5-x86/Dockerfile
gcc_5.2/Dockerfile
gcc_5.3/Dockerfile
gcc_5.4/Dockerfile
gcc_5/Dockerfile
gcc_6-x86/Dockerfile
gcc_6.2/Dockerfile
gcc_6.3/Dockerfile
gcc_6.4/Dockerfile
gcc_6/Dockerfile
gcc_7-x86/Dockerfile
gcc_7.2/Dockerfile
gcc_7/Dockerfile
gcc_8-x86/Dockerfile
gcc_8/Dockerfile
update_cmake.py

cmake 3.12

---

README.md
clang_7-x86/build.sh
clang_7-x86/run.sh
clang_7-x86/test.sh
clang_7/build.sh
clang_7/run.sh
clang_7/test.sh

@lasote Some points were not changed.

Fix missed name replacement

---

build.py

- Avoid shell=True when calling docker login
- Update info messages

Run docker login without terminal=True

---

clang_7-x86/Dockerfile
clang_7/Dockerfile

Hi!
I just replaced fixed package versions for Clang 7 by range. 
Let's take a coffee and wait 2h for CI jobs...
Related jobs:
https://travis-ci.org/conan-io/conan-docker-tools/jobs/488938686
https://travis-ci.org/conan-io/conan-docker-tools/jobs/488938687
Regards!

Fix Clang7 images

---

gcc_4.6/Dockerfile
gcc_4.8-x86/Dockerfile
gcc_4.8/Dockerfile
gcc_4.9-x86/Dockerfile
gcc_4.9/Dockerfile
gcc_5-x86/Dockerfile
gcc_5.2/Dockerfile
gcc_5.3/Dockerfile
gcc_5.4/Dockerfile
gcc_5/Dockerfile
gcc_6-x86/Dockerfile
gcc_6.2/Dockerfile
gcc_6.3/Dockerfile
gcc_6.4/Dockerfile
gcc_6/Dockerfile
gcc_7-centos6-x86/Dockerfile
gcc_7-centos6/Dockerfile
gcc_7-x86/Dockerfile
gcc_7.2/Dockerfile
gcc_7/Dockerfile
gcc_8-x86/Dockerfile
gcc_8/Dockerfile

This PR is to fix #95. CMake Conan is not able to detect gcc when CMake detects /usr/bin/c++ as default compiler
closes #95

#95 Force CXX and CC

---

gcc_5-armv7hf/Dockerfile
gcc_5-armv7hf/armhf.list
gcc_6-armv7hf/Dockerfile
gcc_6-armv7hf/armhf.list
gcc_7-armv7hf/Dockerfile
gcc_7-armv7hf/armhf.list
gcc_8-armv7hf/Dockerfile
gcc_8-armv7hf/armhf.list

This is a rebased+squashed version of @ehargitt's https://github.com/conan-io/conan-docker-tools/pull/62

Add foreign architectures for package manager

---

conan_server/Dockerfile

related issue: https://github.com/conan-io/conan/issues/4723

Fix Conan Server startup

---

gcc_7-centos6-x86/Dockerfile
gcc_7-centos6/Dockerfile

Installed the latest versions of autoconf, automake.
fixes #100

#100 Update autoconf and automake

---

README.md
azure-pipelines.yml
build.py
docker-compose.yml
jenkins-jnlp-slave/Dockerfile
jenkins-jnlp-slave/README.md
jenkins-jnlp-slave/centos6/Dockerfile
jenkins-jnlp-slave/install-openjdk-ppa.sh

Building Jenkins slave image with GCC5 on Azure DevOps.
/cc @maheshjfrog

Build Jenkins Slave on Azure

---

README.md
azure-pipelines.yml
clang_8-x86/.dockerignore
clang_8-x86/Dockerfile
clang_8-x86/build.sh
clang_8-x86/run.sh
clang_8/.dockerignore
clang_8/Dockerfile
clang_8/build.sh
clang_8/run.sh
docker-compose.yml

New Clang version is available on LLVM apt repo
closes #97

Add Clang 8 docker image

---

README.md
build.py
clang_3.9-x86/Dockerfile
clang_3.9/Dockerfile
clang_4.0-x86/Dockerfile
clang_4.0/Dockerfile
clang_5.0-x86/Dockerfile
clang_5.0/Dockerfile
clang_7-x86/Dockerfile
clang_7/Dockerfile
gcc_6-armv7hf/armhf.list
gcc_6-armv8/arm64.list
gcc_6-x86/Dockerfile
gcc_6.4/Dockerfile
gcc_6/Dockerfile
gcc_7-armv7hf/armhf.list
gcc_7-armv8/arm64.list
gcc_7-x86/Dockerfile
gcc_7.2/Dockerfile
gcc_7/Dockerfile

Hi!
I can't push into eric:master, so I just created this new PR, which includes his commits.
Changelog: Fix: Use old-releases to download artful packages (#131)
Related PR: #130 
fixes #131 
/cc @Croydon @ericLemanissier

Fix artful OEL

---

README.md
clang_9-x86/.dockerignore
clang_9-x86/Dockerfile
clang_9-x86/build.sh
clang_9-x86/run.sh
clang_9/.dockerignore
clang_9/Dockerfile
clang_9/build.sh
clang_9/run.sh
docker-compose.yml

Add new compiler support: Clang 9
closes #148
Changelog: Feature: New compiler support - Clang 9
/cc @Croydon

Add clang 9

---

README.md

Fix typo [skip ci]

---

azure-pipelines.yml
docker-compose.yml

We didn't build and upload the container so far 😅 
Are we still missing something or are we good to go now?

Build and upload Clang 9 container

---

build.py

upload clang70:latest too

---

conan_tests/Dockerfile

We need PyGithub to run the test suite

Install PyGithub in the _system_ python

---

conan_tests/Dockerfile

No 'meson' in the main docker

---

conan_version.txt

Signed-off-by: Uilian Ries <uilianries@gmail.com>

Bump Conan version to 1.22.2

---

clang_7-x86/Dockerfile
clang_7-x86/sources.list
clang_7/Dockerfile
clang_7/sources.list

Ubuntu cosmic is on its end-of-life and now we should use the old repos list.

Fix Ubuntu cosmic distro

---

README.md

Continuation of conan-io/docs#1580

Warn about images for open-source packaging

---

conan_version.txt

Changelog: Feature: Conan version 1.23.0

Bump Conan version to 1.23.0

---

clang_8-x86/Dockerfile
clang_8-x86/sources.list
clang_8/Dockerfile
clang_8/sources.list
gcc_9-armv7hf/armhf.list
gcc_9-armv8/arm64.list

Changelog: Fix: Disco is EOL. Needed to add old repos
fixes #191

#191 Add old repo for disco

---

conan_version.txt

Changelog: Feature: Conan 1.24.1 releases

Update Conan version to 1.24.1

---

conan_version.txt
gcc_7-mingw/Dockerfile

Changelog: Feature: Conan 1.25.0

Bump Conan version 1.25.0

---

conan_version.txt

Signed-off-by: Uilian Ries <uilianries@gmail.com>

Bump version 1.25.2

---

conan_version.txt

Changelog: Feature: Bump Conan version to 1.26.0

Update Conan verison to 1.26.0

---

conan_version.txt

Changelog: Feature: Bump Conan version to 1.27.1

Bump version to 1.27.1

---

conan_version.txt

Changelog:  Feature: Bump Conan version to 1.27.1
// @uilianries 
To unblock https://github.com/conan-io/conan-center-index/pull/2037 (and probably others)

Bump version to 1.28.1

---

conan_version.txt

Changelog: Feature: Bump Conan version to 1.29.1
this will unblock at least the following:
- https://github.com/conan-io/conan-center-index/pull/2741
- https://github.com/conan-io/conan-center-index/pull/2303
- https://github.com/conan-io/conan-center-index/pull/2301

Bump version to 1.29.1

---

azure-pipelines.yml
build.py
docker-compose.yml

Changelog: Feature: Add Conan Test + Jenkins client for internal usage.
closes #220

Add Docker tests agent image

---

azure-pipelines.yml
clang_11/.dockerignore
clang_11/Dockerfile
clang_11/build.sh
clang_11/run.sh
conan_version.txt
docker-compose.yml

- Add Clang 11 docker image
- Bump Conan to 1.30.2

Add Clang 11

---

conan_version.txt

Changelog: Feature: Bump Conan version to 1.31.2

Bump Conan version to 1.31.2

---

clang_9-x86/Dockerfile
clang_9-x86/sources.list
clang_9/Dockerfile
clang_9/sources.list
gcc_9-x86/Dockerfile
gcc_9-x86/sources.list
gcc_9/Dockerfile
gcc_9/sources.list

fix gcc and clang 9 images

---

conan_test_azure/Dockerfile
conan_tests/Dockerfile
conan_version.txt

Changelog: Feature: Bump Conan version to 1.33.1

Bump Conan version to 1.33.1

---

clang_10/Dockerfile
clang_11/Dockerfile

Add pkg-config for Clang 10 and 11.

Add pkgconfig for clang images

---

conan_server/Dockerfile
conan_version.txt

Bump to latest Conan version 1.35.2

Bump Conan version 1.35.1

---

conan_version.txt

Bump to latest Conan version 1.35.2

Bump Conan version to 1.35.2

---

build.py

Changelog: Feature: Bump Conan client version to 1.37.1

Release Conan 1.37.1

---

build.py

Conan 1.37.2 is available for download:
https://pypi.org/project/conan/1.37.2/

Update Conan patch version to 1.37.2

---

.ci/xenial.jenkinsfile
modern/tests/fixtures/expected.py

After https://github.com/conan-io/conan-docker-tools/pull/280

[xenial] Run tests for base image

---

.ci/xenial.jenkinsfile

It was failing for branches, that variable was only available for PRs.

Fix Jenkins variable

---

README.md
modern/README.md

More align with the purpose of `modern` directory.

[xenial] rework README files

---

modern/tests/fixtures/expected.py
modern/tests/test_build/test_simple.py

Validate linked libs to c and c++ apps

---

build.py

Changelog: Feature: Install Conan 1.39.0

Bump Conan version to 1.39.0

---

modern/README.md

- fix typos for jenkins images

---

README.md

Signed-off-by: Uilian Ries <uilianries@gmail.com>

[skip ci] Mark gcc49 as deprecated

---

.ci/xenial.jenkinsfile
modern/jenkins/Dockerfile
modern/tests/test_installed/test_jenkins.py

closes https://github.com/conan-io/conan-docker-tools/issues/314
... we were not passing all the required arguments to this docker image 🤦

[fix] Pass arguments to jenkins Dockerfile 

---

modern/clang/Dockerfile
modern/gcc/Dockerfile

Required to test https://github.com/conan-io/conan-docker-tools/pull/323

[modern] Use suffix if provided

---

.ci/conan_center_index.jenkinsfile

Changelog: Fix: Do not build Conan 2.0

[hotfix] Skip conan 2.0 from building

---

build.py

Fix missing 'and' operator

---

modern/tests/fixtures/expected.py
modern/tests/test_installed/test_installed.py
modern/tests/utils/version.py

After https://github.com/conan-io/conan-docker-tools/pull/358 it was expected that the new Git version would break current tests.
Here I'm modifying the tests, now we check the minimum boundary for Git, the upper boundary is open.
---
NOTE.- If anyone knows how to install a fixed version, it would be great to hear it 🙌

Git - test minimum version

---

.ci/on_conan_release.jenkinsfile

Source file changed at some point in time

[ci] Fix regex replacement

---

modern/base/Dockerfile
modern/base/conan.lock
modern/base/profile

Related to https://github.com/conan-io/conan-docker-tools/pull/370/files#r803628721
- Why profile file? 
- To generate that lockfile we run:
conan lock create -r conancenter -pr profile --lockfile-out=conan.lock conanfile.txt

Install binutils from GCC5

---

.ci/conan_center_index.jenkinsfile

closes https://github.com/conan-io/conan-docker-tools/issues/376

[modern] Ignore some Conan versions

---

README.md

Deprecate ARM on ReADME

---

modern/base/Dockerfile
modern/tests/test_installed/test_locale.py

Install and configure locale en_US.UTF-8

---

modern/tests/conftest.py

Let´s have a close look to Jenkins output

tests: record all envnames so ANY match will run

---

.ci/Jenkinsfile

Abort when commit title contains skip ci

---

.ci/conan_center_index_legacy.jenkinsfile
.ci/generate_legacy.jenkinsfile
README.md
legacy/build.py
legacy/conan_client/Dockerfile
legacy/conan_server/Dockerfile
legacy/docker-compose.yml

Add conan client image

---

.ci/on_conan_release.jenkinsfile

On new Conan version, update repository files (recovered from https://github.com/conan-io/conan-docker-tools/commit/0533893a4de71a5e5442418fd74ba26396fdbe5d)

On new Conan version, update repository files [skip ci]

---

.ci/generate_legacy.jenkinsfile

That variable `dir` could interfere with jenkins step with the same name

[ci] Fix legacy CI

---

.ci/on_conan_release.jenkinsfile

Failure detected here https://ci.conan.io/job/ConanDockerTools/job/_onConanVersionReleased/28

ci: no script variable

---

.ci/conan_center_index_legacy.jenkinsfile

Just add comment for future us

[ci] Legacy won't create Conan v2 images

---

README.md
modern/README.md

This cleans up the README.md for consistency and readability, and fixes some garbled parts.

Various fixes and tweaks in README.md

---

modern/README.md

Signed-off-by: Uilian Ries <uilianries@gmail.com>

[skip ci] Add GCC12 into docs

---

.ci/generate.jenkinsfile

This was failing when generating new images

[ci] Fix issue when tagging images as latest [skip-ci]

---

.ci/conan_center_index.jenkinsfile
.ci/generate.jenkinsfile

Hotfix to avoid building all those pre-releases.

Avoid building Conan 2.0 pre-releases

---

.ci/conan_center_index.jenkinsfile
.ci/generate.jenkinsfile

Avoid building older releases first.

Build newer Conan version first

---

.ci/conan_center_index_legacy.jenkinsfile
.ci/generate_legacy.jenkinsfile

Signed-off-by: Uilian Ries <uilianries@gmail.com>Changelog: (Feature | Fix | Bugfix): Describe here your pull request

Set docker buildkit

---

modern/docker-compose.yml

Changelog: Bugfix
Fixes https://github.com/conan-io/conan-docker-tools/issues/517

[bugfix] Update modern/docker-compose.yml to work with docker-compose v2.17+

---

legacy/jenkins-jnlp-slave/Dockerfile
modern/jenkins/Dockerfile

update PATH to find new Java first

---

README.md

[ci skip] Fix typos in README.md tables

---

.ci/conan_center_index.jenkinsfile

Sorting a list in Jenkins is hard, need to be CPS and implement own our custom method, because we can't add a class for version.

Fix sorted list when building Conan v2

---

.ci/conan_center_index_legacy.jenkinsfile

Do not parse the build version

Fix CI build legacy

---

modern/README.md

Changelog: (Feature | Fix | Bugfix): Fix small typo in modern images README

Fix small typo in modern images README

---

modern/README.md

Changelog: (Fix): Update boost install/build command so it works correctly with Conan 2

Update readme in accordance with Conan 2
