README.md, gcc_4.6/Dockerfile, gcc_4.8/Dockerfile, gcc_4.9/Dockerfile, gcc_5.2/Dockerfile, gcc_5.3/Dockerfile, gcc_5.4/Dockerfile, gcc_6.2/Dockerfile, gcc_6.3/Dockerfile, gcc_6.3/build.sh, gcc_6.3/run.sh, rebuild_and_upload.py
This PR adds a Ubuntu 17.04 container with GCC 6.3.
Also it updates CMake to v3.7.2 in all containers.
In contrast to the other containers I run most of the commands in one RUN.
This reduces the Docker layers and therefore the size of the container.
Example build log can be found here https://hub.docker.com/r/croydon/conan-gcc6-3-docker-test/builds/b2ffwq6qne4baxvdbmcyh3d/
=> Support GCC 6.3

build.py, conan_server/Dockerfile, gcc_7.2/Dockerfile, testimage/Dockerfile
Hi!
* After to install g++-7.2 the system doesn't solve c++ and g++ default names, so I used *update-alternatives* for that. 
* Also, when we need to build a C++ package for x86, the header *asm/error.h* is not found. I added *linux-libc-dev:i386* to solve that
* To make sure for next changes, I added a c++ package build (GTest). Unfortunately, conan-center doesn't provide any C++ package, only header only or Poco, but Poco is huge for a simple test. So, I added conan-community. 
Regards
=> Hotfix for GCC 7.2

build.py, clang_5.0/Dockerfile, docker-compose.yml, gcc_4.9/Dockerfile
Hi!
This PR brings some important fixes and improvements.
* As discussed at #27, I moved from vivid to xenial
* Docker compose has some problem to execute under Travis environment, so I reverted to use docker exec when necessary
* Improved Clang image test to build both zlib and GTest using libstdc++ and libc++
* Fixed Clang 5.0, see: https://github.com/conan-io/conan-package-tools/issues/124
* After to add libc++ test, clang-5.0 failed to build using arch=x86. There is a known bug, as workaround I made a symbolic link to locale.h -- I found this solution at Ubuntu forum.
Regards!
Closes #27
=> Hotfix Clang 5.0

.travis.yml, README.md, clang_3.8/Dockerfile, clang_3.8/sources.list, clang_3.9/Dockerfile, clang_3.9/sources.list, clang_4.0/Dockerfile, clang_4.0/sources.list, clang_5.0/Dockerfile, docker-compose.yml, gcc_4.9/Dockerfile, gcc_6.2/Dockerfile, gcc_6.2/sources.list, gcc_6.3/Dockerfile, gcc_6.3/sources.list
Hi!
I updated all clang images to use Ubuntu 17.10 (artful) as base to fix Zesty EOL. Also, artful will end in the middle of this year.
I tried to use Bionic, but there is an error when it try to install lib32stdc++6. Bionic is under development, so I want to update all images in April.
Also, I just removed all package versions because we need to fix clang and put Bincrafters back on the rails. But I promise that I will restore package versions during #31 
Regards!
=> Fix Clang images (#32)

gcc_6-i386/Dockerfile, gcc_6/Dockerfile, gcc_7-i386/Dockerfile, gcc_7/Dockerfile
lasote/conangcc6 and lasote/conangcc7 images has no /usr/include/xlocale.h (same for i386 images)
as result cpprestsdk fails to build:
https://travis-ci.org/bincrafters/conan-cpprestsdk/jobs/342936065
```
sse4@sse4-VirtualBox:~/conan$ docker run --rm -it lasote/conangcc5
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.
conan@9ac51cae25b0:~$ file /usr/include/xlocale.h
/usr/include/xlocale.h: ASCII text
```
```
sse4@sse4-VirtualBox:~/conan$ docker run --rm -it lasote/conangcc6
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.
conan@f3f704782a3a:~$ file /usr/include/xlocale.h
/usr/include/xlocale.h: cannot open `/usr/include/xlocale.h' (No such file or directory)
```
``` …
```
=> - create /usr/include/xlocale.h

clang_3.8/Dockerfile, clang_3.9-x86/Dockerfile, clang_3.9/Dockerfile, clang_4.0-x86/Dockerfile, clang_4.0/Dockerfile, clang_5.0-x86/Dockerfile, clang_5.0/Dockerfile, clang_6.0-x86/Dockerfile, clang_6.0/Dockerfile, conan_server/Dockerfile, gcc_4.6/Dockerfile, gcc_4.8/Dockerfile, gcc_4.9-x86/Dockerfile, gcc_4.9/Dockerfile, gcc_5-x86/Dockerfile, gcc_5.2/Dockerfile, gcc_5.3/Dockerfile, gcc_5.4/Dockerfile, gcc_5/Dockerfile, gcc_6-x86/Dockerfile, gcc_6.2/Dockerfile, gcc_6.3/Dockerfile, gcc_6.4/Dockerfile, gcc_6/Dockerfile, gcc_7-x86/Dockerfile, gcc_7.2/Dockerfile, gcc_7/Dockerfile, gcc_8-x86/Dockerfile, gcc_8/Dockerfile
This PR brings:
- Update ALL images with subversion package (SVN)
- Update Conan docker image to version 1.6.0
closes #47
=> #47 include subversion in images

gcc_4.8/Dockerfile, gcc_4.9-x86/Dockerfile, gcc_4.9/Dockerfile
- Run lsb_release beased on generic python version
- Allow Python2 be installed by system and dont break things
Related issue: #73
=> #73 Fix lsb_release for old distros

.travis.yml, build.py, docker-compose.yml, gcc_7-centos6-x86/.dockerignore, gcc_7-centos6-x86/Dockerfile, gcc_7-centos6-x86/build.sh, gcc_7-centos6-x86/cloudlinux.repo
Hi!
This new image is the support for CentOS 6 x86.
- Why did I replace cmake_installer by ninja_installer?
ninja_installer detected an error during centos cross-building (thanks to @SSE4). It could works better for regression tests.
- Why did I adde cloudlinux repo?
Unfortunately, Cent OS 6 doesn't not offer i386 package repo, thus devtoolset-7 is not available for download.
- Is it possible cross-build to x86 running centos6-x86_64
No. The package `devtoolset-7` is not available for i386. We could include cloudlinux repo and install, but this results in many conflicts for the amd64 version.
EDIT:
gcc4.6 is not able to build ninja installer, so I reverted to cmake_installer again.
Regards!
=> Docker image CentOS 6 x86

README.md
Hi!
It's just a little patch for Cent OS 6 x86, including information in README.
No CI required.
=> Include CentOS6 x86 in README [skip ci]

conan_server/Dockerfile
- The typed-ast 1.3.0 requires gcc to be built.
The package is built and all compiler stuff is removed.
The image size now is 121MB (inflated), +5MB than 1.12.3
=> Fix Conan Server image

gcc_7-centos6-x86/Dockerfile, gcc_7-centos6-x86/sudo, gcc_7-centos6/Dockerfile, gcc_7-centos6/sudo
Fixes conan-io/conan-docker-tools#105
Tested on my local machine:
```
$ docker build --no-cache  -t conanio/gcc7-centos6_myversion .
$ docker run -t -i --rm -v /tmp:/home/conan/project:Z conanio/gcc7-centos6_myversion /bin/bash
[conan@48c653b979fa ~]$ sudo -A ls
project
```
=> Fix sudo script in gcc_7-centos6 and gcc_7-centos6-x86

azure-pipelines.yml, docker-compose.yml, gcc_5-armv8/.dockerignore, gcc_5-armv8/Dockerfile, gcc_5-armv8/arm64.list, gcc_6-armv8/.dockerignore, gcc_6-armv8/Dockerfile, gcc_6-armv8/arm64.list, gcc_7-armv8/.dockerignore, gcc_7-armv8/Dockerfile, gcc_7-armv8/arm64.list, gcc_8-armv8/.dockerignore, gcc_8-armv8/Dockerfile, gcc_8-armv8/arm64.list
A single issue occured during gcc5 build, where update-alternatives to /usr/bin/aarch64-linux-gnu-gcov-dump-5 couldn't find the executable even after installing the gcc-5-aarch64-linux-gnu package. The offending line line was simply removed. @SSE4 please let me know if this is acceptable and I will update the README.md.
On each gcc version I locally run the following, without any issues:
```
docker run -ti conanio/gcc*-armv8 bash -c "conan install lz4/1.8.3@bincrafters/stable --build missing"
```
This addresses #109
=> Feature/armv8: Add Dockerfiles for armv8 architecture, from gcc5 to gcc8.

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .github/settings.yml, .github/stale.yml
- Add Contributing guide from CPT
- Add issues template from CPT
- Add issues labels from CPT
TIL: [How to skip CI on Azure DevOps](https://github.com/Microsoft/azure-pipelines-agent/issues/858#issuecomment-475768046)
EDIT: `***NO_CI***` does not work!
=> Add Template for Github issues ***NO_CI***

README.md, azure-pipelines.yml, build.py
Hi!
Since we are having trouble with CDT to re-use basic images (e.g. conanio/gcc8), this PR tries to unify many CI jobs as possible.
Before this PR I tried 2 other alternatives, but without sucess:
- Using Azure stages to build first all base images, and a second stage to build specialized images. It didn't work because it's not possible retrieving a docker image from previous stage. The experiment can be verified [here](https://github.com/uilianries/conan-docker-tools/blob/feature/multiple-stage/azure-pipelines.yml).
- Docker [multistage build](https://docs.docker.com/develop/develop-images/multistage-build/) is an incredible feature, so why not creating an unique Docker recipe with many different images? So I've created a docker …
=> One CI job, many docker images

gcc_7-centos6-x86/Dockerfile, gcc_7-centos6/Dockerfile
- Build newest stable Git version for CentOS6
Changelog: Feature: Install Git 2.20.0 for CentOS6
closes https://github.com/conan-io/conan-docker-tools/issues/141
=> #141 Build newest Git version

build.py
Since Clang 7 is available as clang 7.0 in Conan settings and LLVM just released Clang 7.1, I think this alias can help to build with CPT:
CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=clang70
Original discussion: https://cpplang.slack.com/archives/C41CWV9HA/p1568472642006400
/cc @Minimonium @ericLemanissier 
Changelog: Feature: Create alias for clang7 as clang70
=> Create alias for clang 7

build.py
Part of log after building with this patch:
```
2019-10-24 09:29:50,395 [INFO]: Show Docker image conanio/clang7:latest size:
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
conanio/clang7      latest              fcdc6a30c8a1        2 minutes ago       858MB
2019-10-24 09:29:50,667 [INFO]: Show Docker image conanio/clang7:latest info:
[
{
"Id": "sha256:fcdc6a30c8a17a56609c708a44b63e509156137ec0c3ab2e6533aaa1b9543982",
"RepoTags": [
"conanio/clang70:1.19.2",
"conanio/clang70:latest",
"conanio/clang7:1.19.2",
"conanio/clang7:latest"
],
"RepoDigests": [],
"Parent": "sha256:56784d6034226c3774cb076384673dcea2646f2f2767783d923b5a340f31add8",
"Comment": "",
```
As you can see, both versions (latest and 1.19.2) have an individual tag.
Changelog: Fix: Add tag …
=> Fix clang70 tag

gcc_4.8-x86/Dockerfile, gcc_4.8/Dockerfile, gcc_4.9-x86/Dockerfile, gcc_4.9/Dockerfile
One good practice for Docker is installing APT package to a specific version, however, on Ubuntu it's not possible, since all distro version drop a version and switch to new old, which make impossible to install an old version.
As we don't provide Docker images based on revisions, but in Conan versions, we should use dynamic APT package versions, since we build all images again for each new Conan release.
This problem is well known, so on this PR I've removed all versions for GCC 4.8 and GCC 4.9 which are based on Ubuntu 14.04.
Changelog: Fix: Do not force apt package version for old Ubuntu distros
This PR is required by: #169 #168
=> Remove package version for old gcc images

azure-pipelines.yml, build.py, conan_test_azure/Dockerfile, conan_tests/Dockerfile, docker-compose.yml
There are 2 main different test images, but basically they are the same thing:
- conantests: It gets conanio/gcc5 and install python3-x
- conantestazure: Build an entire Docker image
Those images contain from Python-3.4 to Python-3.8 installed, but you need to configure what you want when running those containers:
alias python=python3.8
Changelog: Feature: Build Conan test images and deploy
Related PR: #168 #153
=> Build Conan tests images

conan_tests/Dockerfile
We need `virtualenv --python "/usr/bin/python3.8"` to work inside the image out of the box
Tip from here https://github.com/deadsnakes/issues/issues/82#issuecomment-478288319
=> Install 'python3.8-distutils' too

conan_tests/Dockerfile
=> Meson is needed, Jenkins cannot install it

README.md, azure-pipelines.yml, build.py, clang_10/.dockerignore, clang_10/Dockerfile, clang_10/build.sh, clang_10/run.sh, docker-compose.yml
Changelog: Feature: Add Clang 10 container image
__________________________________
I decided to go with the upstream LLVM APT repository this time, as they offer builds for older LTS versions of Ubuntu too.
Ubuntu itself is currently only offering Clang 10 binaries for Ubuntu 20.04. Using this would mean a brand new glibc version which causes that the built binaries are compatible with just very few distribution versions out there....
Ubuntu Bionic seems currently to be a fair compromise between not too old and not too new.
I also re-structured the Dockerfile a little bit differently compared to previous Clang containers, so that it is more clear what packages are installed why.
LLVM, Python and CMake versions are now also specified via environment variables at the beginning of the …
=> Add Clang 10 image

jenkins-jnlp-slave/DockerfileAgent
Changelog: Fix: Conan Test Agent requires root user by default
As the propose of Conan Test Agent is running dind (Docker-in-Docker), it requires the access to unix socket file, but also only root user is able to write there. As there is no usage for volumes and file sharing on this container, the root user should not be a problem.
This PR consists in removing any sudo and adding root as the default user.
=> Conan test agent should be root

clang_9-x86/Dockerfile, clang_9-x86/sources.list, clang_9/Dockerfile, clang_9/sources.list, gcc_9-x86/Dockerfile, gcc_9-x86/sources.list, gcc_9/Dockerfile, gcc_9/sources.list
This simplifies the use of conan package tools in CI: with this change one can set a matrix job setting only the docker image to use, and CPT automatically picks up the proper GCC or clang version, based on the environment variables set by the image
=> set CONAN_CLANG/GCC_VERSIONS env var

build.py, clang_10/Dockerfile, clang_11/Dockerfile, clang_3.9/Dockerfile, clang_4.0/Dockerfile, clang_5.0/Dockerfile, clang_6.0/Dockerfile, clang_7/Dockerfile, clang_8/Dockerfile, clang_9/Dockerfile, gcc_10/Dockerfile, gcc_4.9/Dockerfile, gcc_5/Dockerfile, gcc_6/Dockerfile, gcc_7/Dockerfile, gcc_8/Dockerfile, gcc_9/Dockerfile
As Conan Center Index is doing internal changes, JFrog CLI will be required.
I didn't add for x86 images because they are optional and not used by CCI.
=> Install JFrog CLI for all CCI images

README.md, azure-pipelines.yml
Some images are no longer used by CCI and now caused errors to https://github.com/conan-io/conan-docker-tools/pull/249 because we need to install JFrog CLI. 
We could install, but thinking about, I think it's a good opportunity to remove old images which are no longer used.
We can keep the recipes, as for Windows, so anyone is able to build from sources. But distributing will no longer available.
closes #240
/cc @Croydon
=> Deprecated old docker images

build.py
Just to enforce all 1.35.2 images are running the correct Conan client version.
=> Rebuild all 1.35.2 for aligment

.gitignore, azure-pipelines.yml, modern/run_pytest.sh, modern/tests/conftest.py, modern/tests/fixtures/container.py, modern/tests/fixtures/expected.py, modern/tests/test_versions/test_installed.py, modern/tests/utils/docker_container.py
Getting some bits from here: https://github.com/uilianries/conan-docker-tools/pull/5
---
This is the proposal in this PR (although it doesn't modify anything already existing):
* Get rid of all the Python code to generate docker images (remove dependency of `conan` and `conan-package-tools`). Use plain and well-known docker commands and mechanisms to generate the images. Users should be able to understand this repository and generate the images without the need of inspecting/installing any `.py` file or Python itself.
* Replace current testing with other that uses only the `pytest` framework to orchestrate the commands. Get rid of `.sh` scripts and `run.py` scripts to run the tests and the checks. New test framework will operate on a given image name:
```
pytest modern/tests --image …
```
=> Propose new test framework for the docker images

clang_10/Dockerfile, clang_11/Dockerfile, clang_3.9/Dockerfile, clang_4.0/Dockerfile, clang_5.0/Dockerfile, clang_6.0/Dockerfile, clang_7/Dockerfile, clang_8/Dockerfile, clang_9/Dockerfile, gcc_10/Dockerfile, gcc_11/Dockerfile, gcc_4.9/Dockerfile, gcc_5/Dockerfile, gcc_6/Dockerfile, gcc_7/Dockerfile, gcc_8/Dockerfile, gcc_9/Dockerfile
The current JFrog CLI url returns HTTP 403 Error. Let's use the official script.
=> Fix Jfrog cli download

build.py
Conan 1.38.0 is out, let's update it here too.
=> Bump Conan version to 1.38.0

modern/tests/fixtures/expected.py, modern/tests/test_installed/test_installed.py, modern/tests/test_installed/test_not_installed.py
Some tools like `pkg-config` can not be removed, because they are largely used in Conan Center, if we remove it, first we need to update ALL recipes in CCI, otherwise, those new images will break many users.
Some tools like vim, used to be installed in the past, for "development" when creating a new recipe. At some point we removed it, and we don't want it again.
closes #287
=> Validate installed and not installed tools for new Docker images

modern/base/Dockerfile, modern/clang/Dockerfile, modern/gcc/Dockerfile, modern/tests/test_installed/test_conan.py
IMO, it would be useful to use the defaults that are aligned with the future.
Closes https://github.com/conan-io/conan-docker-tools/issues/304
=> conan config: enable revisions, use libstdc++ by default in gcc

clang_11/Dockerfile
libc++-dev is version 6: https://packages.ubuntu.com/bionic/libc++-dev
=> clang11: update libc++

azure-pipelines.yml, gcc_4.6/Dockerfile, gcc_4.8-x86/Dockerfile, gcc_4.8/Dockerfile, gcc_4.9-armv7/Dockerfile, gcc_4.9-armv7hf/Dockerfile, gcc_4.9-x86/Dockerfile, gcc_4.9/Dockerfile
Changelog: Bugfix: Fix certificate error for old gcc images 4.8 and 4.9
The OpenSSL version installed for Ubuntu Trusty is old (1.0.2) and can not be used with new certificates.
Related to https://github.com/conan-io/conan/issues/9695
Thus, this PR:
- Remove DST_Root_CA_X3.pem 
- Bump Python 3.6.7 to 3.6.15 for old images
- Install and build OpenSSL 1.1.1l
=> Fix certificate error for old GCC images 4.8 and 4.9

.ci/on_conan_release.jenkinsfile
So we don't forget anything whenever there is a new Conan release. This job will be triggered by the Conan release process.
=> CI to generate docker images after a new Conan release

.ci/on_conan_release.jenkinsfile
Looks like Pypi is not refreshed so fast.
=> Wait a bit before starting to generate docker images

build.py, clang_7/Dockerfile, clang_8/Dockerfile, clang_9/Dockerfile, gcc_10/Dockerfile, gcc_11/Dockerfile, gcc_4.9/Dockerfile, gcc_5/Dockerfile, gcc_6/Dockerfile, gcc_7/Dockerfile, gcc_8/Dockerfile, gcc_9/Dockerfile
The `lsb_release` command is hardcoded to use system's python, not the installed pyenv. Also, the module `lsb_release.py` is not available as python package, only from apt, so the recommended way is creating a link to find the module from system.
fixes #364
=> Fix lsb_release command

build.py
- Update legacy images to 1.44.1
- Support CONAN_VERSION as environment variable, so we can re-run CI without new commit.
=> Accept Conan version as env var

modern/base/Dockerfile, modern/gcc/Dockerfile
Changelog: (Feature): Allow to use Ubuntu 18.04 as a base image
=> Allow to use Ubuntu 18.04 as a base image

modern/gcc/Dockerfile, modern/tests/test_installed/test_gcc.py
fixes https://github.com/conan-io/conan-docker-tools/issues/405
No more errors when building imake:
```
conan@6a163f810cb0:~$ conan install imake/1.0.8@ --build=imake --profile:host=default --profile:build=default                
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
imake/1.0.8: Forced build from source
Installing package: imake/1.0.8
Requirements
imake/1.0.8 from 'conancenter' - Cache
xorg-macros/1.19.3 from …
```
=> Do not override cpp and c++ installation 

.ci/conan_center_index.jenkinsfile
For prerelease versions (`2.0.0a6`) it is not enough to join the major.minor.patch components, it requires all the version identifier. Using strings instead of tokens simplifies it.
=> Use strings to store versions

legacy/gcc_10/Dockerfile, legacy/gcc_11/Dockerfile, legacy/gcc_4.9/Dockerfile, legacy/gcc_6/Dockerfile, legacy/gcc_7/Dockerfile, legacy/gcc_8/Dockerfile, legacy/gcc_9/Dockerfile
Replaces https://github.com/conan-io/conan-docker-tools/pull/164
closes #161
closes #164
=> Fix gcov version for legacy images

.ci/generate_legacy.jenkinsfile
Don't create deprecated Jenkins images:
* GCC 11 (and above) is already using modern images
* Clang 12 (and above) is using modern images.
These are the relevant snippets from CCI configuration (please, double check):
```
node_labels:
Linux:
x86_64:
"gcc":
default: "linux_gcc_${compiler.version}"
"11": "linux_gcc_${compiler.version}_ubuntu16.04"
"clang":
default: "linux_clang_${compiler.version}_ubuntu16.04"
"11": "linux_clang_${compiler.version}"
```
=> [ci] Fix typo + Do not create _deprecated_ Jenkins images 

legacy/clang_10/Dockerfile, legacy/clang_11/Dockerfile
Related to https://github.com/conan-io/conan-center-index/pull/10795
lsb_release is an APT package which wants the python from the system, not from pyenv, which causes a mess when trying to execute from pyenv version.
As workaround, we link the original script to pyenv folder, so we "install" lsb_release to our global python version.
We already did it in the past, but forgot to add for new clang images. For modern images it's not required, lsb_release works there.
=> Patch lsb_release for Clang 10 and Clang 11

.github/stale.yml
The CDT is not so active to start to close issues and PR every months. Some questions need months to get feedback or even non prioritized features can take many months. Let's update the stale bot to wait 6 months to put as `stale` state + 3 months to close a staled issue.
=> [skip ci] update stale time

modern/clang/Dockerfile
There is no general option to build on LLVM tools only, instead, there is the cmake option `LLVM_BUILD_TOOLS` which build all tools in case the command `ninja all` is executed, however that ninja command builds more things that we need. 
On the other hands, we are very explicit (explicit is better than implicit) now and we know exactly what is installed in our image.
The llvm tool list was collected from the docker image `conanio/clang10` so we considered "legacy" tools.
closes #442
=> [modern] Build and install LLVM tools

.ci/conan_center_index.jenkinsfile, .ci/conan_center_index_legacy.jenkinsfile
CDT build specific images for Conan Center based on the official Conan version running.
We moved the location of the current version.
=> Fix conan version location

modern/base/Dockerfile
All dev ubuntu packages should be consumed from Conan Center, otherwise, our package can consume from system by mistake.
All removed packages are present in Conan Center.
Let's start with modern, then, we can go with legacy.
/cc @jcar87
=> Remove system dev packages for modern images

modern/gcc/Dockerfile
Fix: Wrong option disabled for GCC build is not check by configure. Maybe GCC bootstrap does it, but it would increase our build time by 1h at least.
closes #460
/cc @maksim-petukhov
=> [hotfix] GCC build option: nsl should be nls instead

README.md
Changelog: Fix: Remove non-existing images from README.md
Some of the images linked in README.md don't exist on Docker Hub anymore. I suggest to either remove them from README.md or make them available on Docker Hub again.
=> Remove non-existing images from README.md

.ci/on_conan_release.jenkinsfile
Avoid user's email and use a generic email instead, so we don't need to replace in the future.
=> Use conancenter email

.ci/generate.jenkinsfile
Changelog: Fix: Generate conan v2 images with their real version as tag
Right now is getting complicated to know what beta version the label `2.0.0-pre` ins dockerhub has. At the point that, even in c3i, the version is not consistent and we are failing to have control over that version.
In this PR, I remove the `-pre` logic and just leave the version untouched to be pushed as the image label.
=> [ci] Tag conan v2 images with real name [skip-ci]

legacy/android-clang_14/Dockerfile, modern/README.md
The documentation does not reflect the current usage with Ubuntu 16.04
=> [skip-ci] Keep Ubuntu 16.04 supported for now

.ci/conan_center_index.jenkinsfile
The CDT CI job is not generating Conan 2.0.0-beta10 because, the validation method is checking wrong indexes. As result, it always build the latest version available on json list provided by pypi.
=> [hotfix] Build Conan 2.0 beta higher than pre-version 9

.ci/conan_center_index.jenkinsfile, .ci/generate.jenkinsfile
Conan 2.0 is now stable and need to be built for every new client release.
=> Build conan 2.0 by default

.ci/conan_center_index.jenkinsfile
To avoid extra CI resource, let's build only 3 latest versions of Conan 2.x available.
Plus, continue to build the latest 1.x version available for CCI.
=> [ci] Build only 3 latest versions of Conan 2.x

.ci/generate.jenkinsfile
The jenkins images should be `latest-4.9`, not `latest-<conan-version>-4.9`
=> Fix tag name for jenkins images

modern/gcc/Dockerfile
As mentioned in
https://github.com/conan-io/conan-center-index/issues/18809, currently some conan shared libraries are build without .note.gnu.build-id note and thus one cannot link separated debug info ELF file with the shared library. It is something CPack complains about: https://github.com/Kitware/CMake/blob/master/Modules/Internal/CPack/CPackDeb.cmake#L231
GCC documentation of the added option:
https://gcc.gnu.org/install/configure.html
Changelog: Bugfix: Describe here your pull request
=> gcc: always pass --build-id to linker

.ci/conan_center_index.jenkinsfile, .ci/conan_center_index_legacy.jenkinsfile
Frequently we have problems when generating Docker images, mainly when installing APT packages, resulting in the entire build failed. This hotfix introduces retry context to avoid more delays when having a failed job.
=> Introduce retry for builds when generating Docker images in CI

.ci/generate_legacy.jenkinsfile
The docker images in the legacy folder to Clang are no longer used in ConanCenterIndex.
They are no longer mandatory for CI Conan.
=> [ci] Skip building clang for legacy images

legacy/docker-compose.yml, legacy/gcc_5/Dockerfile, legacy/gcc_7/Dockerfile, legacy/gcc_9/Dockerfile
The only still active legacy GCC images: GCC 5, 7 and 9 are installing x86 support, but it's not used in CCI since few years.
This PR removes those steps that 32-bit libraries and tools.
Plus, it splits the Docker recipe in several steps. It will result in a bit bigger image, but will be much easier to debug when failing to build. Errors occurs with frequency, or because a networking error, or an outdated certified, etc.
Plus, fixed the docker-compose file with not supported builds (This file is not used by the CI).
It should be only merged after the PR #566
=> Do not support x86 in active legacy images

.ci/conan_center_index.jenkinsfile
The Conan version should be parsed to a list, then converted to a string when needed.
=> [bugfix] Fix Conan version parse in Jenkins

.ci/generate.jenkinsfile
Using string multi line in Jenkins is hard when passing values directly to the web interface and very fragile when using re-build action. Parsing string with commas is safer.
=> [bugfix] Compiler versions param should be string

README.md
Add more context how to consume Docker images and try to clarify (even more) that only images used by ConanCenterIndex CI are actually maintained.
Plus, fix the badge URL. 
closes #580
=> [docs] [skip-ci] Add how to consume Docker images

modern/gcc/Dockerfile, modern/gcc/specs
Drop a file called `specs` in the directory where `gcc` looks for it, such that the the file passes `--as-needed` when linking, as it is configured in Ubuntu.
The directory was derived by calling:
```
gcc -print-search-dirs \
| sed -n -e '/^libraries: =/ {s/.*: =//; s/:/\n/g; p}' \
| xargs realpath -q \
| awk '{if (!seen[$0]) print; seen[$0] = 1;}'
```
as instructed in https://wozniak.ca/blog/2024/01/09/1/
The specfile is a copy of `gcc -dumpspecs`, but with the necessary changes to pass `--as-needed` when linking. Even after this change, the output of `gcc -dumpspecs` can be compared/diffed with the contents of this file.
More on `--as-needed`: https://bnikolic.co.uk/blog/gnu-ld-as-needed.html
This fixes issues in Conan Center CI - and avoids the linker encoding `DT_NEEDED` entries for …
=> gcc: pass "--as-needed" when linking

modern/README.md
Changelog: (Fix): Fix icons for Docker image status (supported images had warning signs instead of checkmarks)
=> Fix icons for Docker image status
